power <- read.csv("C:/Users/Administrator/My Cubby/Coursera/DataScience/Exploratory Data Analysis/P_01/R/household_power_consumption.txt", sep=";", stringsAsFactors=FALSE)
powers=subset(power,Date=="1/2/2007"|Date=="2/2/2007")
powers$datetime =paste(powers$Date," ",powers$Time)
powers$datetime2=as.POSIXct(powers$datetime,format="%d/%m/%Y %H:%M:%S")
powers$Global_active_power=as.numeric(powers$Global_active_power)

png(filename = "plot2.png",width=480, height=480)
par(mfrow = c(1, 1))
with(powers,plot(Global_active_power~datetime2,type="l",xlab="",ylab="Global Active Power (kilowatts)"))
dev.off()